version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ml_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mldb
    ports:
      - "5432:5432"